[theme]
primaryColor = "#007bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
showErrorDetails = false

[server]
maxUploadSize = 200
port = 8501
headless = true
